#!/bin/bash

echo "Comparing benchmarks without and using bounded.Pool. The results should be similar."
echo ""

echo "Running example without bounded.Pool"
go run examples/without_pkg/md5_all.go $GOPATH/src/github.com

echo "Running example using bounded.Pool"
go run examples/bounded/md5_all.go $GOPATH/src/github.com/
